name: arr-stack
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 7878:7878
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/radarr-config:/config
      - /mnt:/storage
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/sonarr-config:/config
      - /mnt:/storage
    ports:
      - 8989:8989
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8686:8686
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/lidarr-config:/config
      - /mnt:/storage
    restart: unless-stopped

  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 8386:8686
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/whisparr-config:/config
      - /mnt:/storage
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/prowlarr-config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    ports:
      - "8191:8191"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/overseerr-config:/config
    ports:
      - 5555:5055
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
