name: factorio
services:
  upnp:
    image: ghcr.io/vleeuwenmenno/auto-upnp:latest
    restart: unless-stopped
    network_mode: host
    environment:
      UPNP_DURATION: 86400  # 24 hours in seconds
      PORTS: | 
        [
          {"port": 34197, "protocol": "udp"}
        ]

  server-manager:
    image: "ofsm/ofsm:latest"
    container_name: "factorio-server-manager"
    restart: "unless-stopped"
    environment:
      - "FACTORIO_VERSION=stable"
    ports:
      - "5080:80"
      - "34197:34197/udp"
    volumes:
      - "./fsm:/opt/fsm-data"
      - "./saves:/opt/factorio/saves"
      - "./mods:/opt/factorio/mods"
      - "./config:/opt/factorio/config"
      - "./mod_packs:/opt/fsm/mod_packs"
