services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/services/sabnzbd:/config
      - /mnt:/storage
    ports:
      - 7788:8080
    restart: unless-stopped
