name: upnp
services:
  service:
    image: ghcr.io/vleeuwenmenno/auto-upnp:latest
    restart: unless-stopped
    network_mode: host
    environment:
      UPNP_DURATION: 86400  # 24 hours in seconds
      PORTS: |
        [
          {"port": 80, "protocol": "tcp"},
          {"port": 443, "protocol": "tcp"}
        ]