config:
  # Symbolic links to create
  symlinks:
    nix-home-manager:
      source: ~/dotfiles/config/home-manager
      target: ~/.config/home-manager

    # NixOS Configuration
    nixos:
      source: ~/dotfiles/config/nixos/configuration.nix
      target: /etc/nixos/configuration.nix

    # Gitconfig
    gitconfig:
      sources:
        macos: ~/dotfiles/config/gitconfig.macos
        linux: ~/dotfiles/config/gitconfig.linux
        wsl: ~/dotfiles/config/gitconfig.wsl
      target: ~/.gitconfig

    # VSCode settings
    vscode:
      source: ~/dotfiles/vscode/settings.json
      target: ~/.config/Code/User/settings.json
      
    # SSH config
    ssh:
      source: ~/dotfiles/config/ssh/config
      target: ~/.ssh/config

    ssh_config_d:
      source: ~/dotfiles/config/ssh/config.d
      target: ~/.ssh/config.d

    ssh_authorized_keys:
      sources:
        mennos-laptop: ~/dotfiles/config/ssh/authorized_keys/mennos-laptop
        mennos-desktop: ~/dotfiles/config/ssh/authorized_keys/mennos-desktop
        homeserver-pc: ~/dotfiles/config/ssh/authorized_keys/homeserver-pc
      target: ~/.ssh/authorized_keys
      chmod: 600

    # bashrc
    bashrc:
      source: ~/dotfiles/.bashrc
      target: ~/.bashrc

    # Starship config
    starship:
      source: ~/dotfiles/config/starship.toml
      target: ~/.config/starship.toml
  
  # Fonts to install (Mostly tested with Nerd Fonts)
  fonts:
    Hack:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
      name: Hack
    Meslo:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip
      name: Meslo
    JetBrainsMono:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
      name: JetBrainsMono

  git:
    dotfiles:
      url: git@git.mvl.sh:vleeuwenmenno/dotfiles.git
      branch: master
      target: ~/dotfiles

    ssdc_app_v2:
      url: git@github.com:vleeuwenmenno/ssdc_app_v2.git
      branch: master
      target: ~/Projects/Private/ssdc_app_v2

    infra:
      url: git@github.com:tradaware/infra.git
      branch: main
      target: ~/Projects/Work
    

  # Packages to install
  # Note: Uninstalling packages is not supported, if you remove a package from this list it will not be removed from the system!
  #       Likewise with flatpak remotes, apt repositories, etc.
  packages:
    # Supply a git_url and binary to install from source
    cargo:
      rip2:
      fd-find:

    pipx:
      - gnome-extensions-cli
      - bauh
      - shyaml

# No longer supported:
    # apt:
    #   repos:
    #   apps:
    #     - bash
    #     - bash-completion
    #     - solaar
    #     - git
    #     - curl
    #     - wget
    #     - gpg
    #     - nala
    #     - ca-certificates
    #     - gnupg-agent
    #     - software-properties-common
    #     - apt-transport-https
    #     - vim
    #     - sl
    #     - jq
    #     - gh
    #     - libglvnd-dev
    #     - libwayland-dev
    #     - libseat-dev
    #     - libxkbcommon-dev
    #     - libinput-dev
    #     - udev
    #     - dbus
    #     - liblzma-dev
    #     - libreadline-dev
    #     - libdbus-1-dev
    #     - libsystemd-dev
    #     - libpixman-1-dev
    #     - libssl-dev
    #     - libflatpak-dev
    #     - libpulse-dev
    #     - libexpat1-dev
    #     - libfontconfig-dev
    #     - libfreetype-dev
    #     - mold
    #     - clang
    #     - libgtk-3-dev
    #     - gcc
    #     - gcc-mingw-w64
    #     - btop
    #     - htop
    #     - libgbm-dev
    #     - libclang-dev
    #     - libsecret-1-dev
    #     - libpipewire-0.3-dev
    #     - libpam0g-dev
    #     - openssh-server
    #     - build-essential
    #     - flatpak
    #     - meson
    #     - pipx
    #     - python3-nautilus
    #     - gettext
    #     - fzf
    #     - fastfetch
    #     - screenfetch
    #     - screen
    #     - code
    #     - 1password
    #     - 1password-cli
    #     - flameshot
    #     - cmake
    #     - libsqlite3-dev
    #     - libudev-dev
    #     - libncursesw5-dev
    #     - libgdbm-dev
    #     - libc6-dev
    #     - libbz2-dev
    #     - libffi-dev
    #     - tk-dev
    #     - cmatrix
    #     - toilet
    #     - oneko
    #     - libaa-bin
    #     - libcurses-perl
    #     - xdotool
    #     - xclip
