config:
  # Symbolic links to create
  symlinks:
    nix-home-manager:
      source: ~/dotfiles/config/home-manager
      target: ~/.config/home-manager

    # NixOS Configuration
    nixos:
      source: ~/dotfiles/config/nixos/configuration.nix
      target: /etc/nixos/configuration.nix

    # Gitconfig
    gitconfig:
      sources:
        macos: ~/dotfiles/config/gitconfig.macos
        linux: ~/dotfiles/config/gitconfig.linux
        wsl: ~/dotfiles/config/gitconfig.wsl
      target: ~/.gitconfig

    # Yubico u2f keys
    u2f:
      sources:
        mennos-laptop: ~/dotfiles/secrets/yubico/u2f.work.keys
        mennos-desktop: ~/dotfiles/secrets/yubico/u2f.personal.keys
        mennos-gamingpc: ~/dotfiles/secrets/yubico/u2f.personal.keys
        homeserver-pc: ~/dotfiles/secrets/yubico/u2f.personal.keys
      target: ~/.config/Yubico/u2f_keys
      chmod: 644

    # VSCode settings
    vscode:
      source: ~/dotfiles/vscode/settings.json
      target: ~/.config/Code/User/settings.json

    # Autostart
    autostart:
      source: ~/dotfiles/config/autostart
      target: ~/.config/autostart
      
    # SSH config
    ssh:
      source: ~/dotfiles/config/ssh/config
      target: ~/.ssh/config

    ssh_config_d:
      source: ~/dotfiles/config/ssh/config.d
      target: ~/.ssh/config.d

    ssh_authorized_keys:
      sources:
        mennos-laptop: ~/dotfiles/config/ssh/authorized_keys/mennos-laptop
        mennos-desktop: ~/dotfiles/config/ssh/authorized_keys/mennos-desktop
        mennos-gamingpc: ~/dotfiles/config/ssh/authorized_keys/mennos-gamingpc
        homeserver-pc: ~/dotfiles/config/ssh/authorized_keys/homeserver-pc
      target: ~/.ssh/authorized_keys
      chmod: 600

    # bashrc
    bashrc:
      source: ~/dotfiles/.bashrc
      target: ~/.bashrc

    # Starship config
    starship:
      source: ~/dotfiles/config/starship.toml
      target: ~/.config/starship.toml
  
  # Fonts to install (Mostly tested with Nerd Fonts)
  fonts:
    Hack:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
      name: Hack
    Meslo:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip
      name: Meslo
    JetBrainsMono:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
      name: JetBrainsMono

  git:
    dotfiles:
      url: git@git.mvl.sh:vleeuwenmenno/dotfiles.git
      branch: master
      target: ~/dotfiles

    ssdc_app_v2:
      url: git@github.com:vleeuwenmenno/ssdc_app_v2.git
      branch: master
      target: ~/Projects/Private/ssdc_app_v2

    infra:
      url: git@github.com:tradaware/infra.git
      branch: main
      target: ~/Projects/Work

  # Packages to install
  # Note: Uninstalling packages is not supported, if you remove a package from this list it will not be removed from the system!
  #       Likewise with flatpak remotes, apt repositories, etc.
  packages:
    # Supply a git_url and binary to install from source
    cargo:
      rip2:
      fd-find:

    pipx:
      - gnome-extensions-cli
      - bauh
      - shyaml
