config:
  # Symbolic links to create
  symlinks:
    nix-home-manager:
      source: ~/dotfiles/config/home-manager
      target: ~/.config/home-manager

    # NixOS Configuration
    nixos:
      source: ~/dotfiles/config/nixos/configuration.nix
      target: /etc/nixos/configuration.nix

    # Gitconfig
    gitconfig:
      sources:
        macos: ~/dotfiles/config/gitconfig.macos
        linux: ~/dotfiles/config/gitconfig.linux
        wsl: ~/dotfiles/config/gitconfig.wsl
      target: ~/.gitconfig

    # Yubico u2f keys
    u2f:
      sources:
        mennos-laptop: ~/dotfiles/secrets/yubico/u2f.work.keys
        mennos-server: ~/dotfiles/secrets/yubico/u2f.personal.keys
        mennos-gamingpc: ~/dotfiles/secrets/yubico/u2f.personal.keys
        homeserver-pc: ~/dotfiles/secrets/yubico/u2f.personal.keys
      target: ~/.config/Yubico/u2f_keys
      chmod: 644

    # VSCode settings
    vscode:
      source: ~/dotfiles/vscode/settings.json
      target: ~/.config/Code/User/settings.json

    # Autostart
    autostart:
      source: ~/dotfiles/config/autostart
      target: ~/.config/autostart
      
    # SSH config
    ssh:
      source: ~/dotfiles/config/ssh/config
      target: ~/.ssh/config

    ssh_config_d:
      source: ~/dotfiles/config/ssh/config.d
      target: ~/.ssh/config.d

    ssh_authorized_keys:
      sources:
        mennos-laptop: ~/dotfiles/config/ssh/authorized_keys/mennos-laptop
        mennos-server: ~/dotfiles/config/ssh/authorized_keys/mennos-server
        mennos-gamingpc: ~/dotfiles/config/ssh/authorized_keys/mennos-gamingpc
        homeserver-pc: ~/dotfiles/config/ssh/authorized_keys/homeserver-pc
      target: ~/.ssh/authorized_keys
      chmod: 600

    # Starship config
    starship:
      source: ~/dotfiles/config/starship.toml
      target: ~/.config/starship.toml


  # Packages to install
  # Note: Uninstalling packages is not supported, if you remove a package from this list it will not be removed from the system!
  #       Likewise with flatpak remotes, apt repositories, etc.
  packages:
    # Supply a git_url and binary to install from source
    cargo:
      fd-find:

    pipx:
      - shyaml
