config:
  # Symbolic links to create
  symlinks:
    # Gitconfig
    gitconfig:
      sources:
        macos: ~/dotfiles/config/gitconfig.macos
        linux: ~/dotfiles/config/gitconfig.linux
      target: ~/.gitconfig
      
    # SSH config
    ssh:
      source: ~/dotfiles/config/ssh/config
      target: ~/.ssh/config

    ssh_config_d:
      source: ~/dotfiles/config/ssh/config.d
      target: ~/.ssh/config.d

    ssh_authorized_keys:
      sources:
        mennos-laptop: ~/dotfiles/config/ssh/authorized_keys/mennos-laptop
        mennos-desktop: ~/dotfiles/config/ssh/authorized_keys/mennos-desktop
        homeserver-pc: ~/dotfiles/config/ssh/authorized_keys/homeserver-pc
      target: ~/.ssh/authorized_keys
      chmod: 600

    # Zshrc
    zshrc:
      source: ~/dotfiles/.zshrc
      target: ~/.zshrc

    # VSCode settings
    vscode:
      source: ~/dotfiles/vscode/settings.json
      target: ~/.config/Code/User/settings.json

    vscode-argv:
      source: ~/dotfiles/vscode/argv.json
      target: ~/.vscode/argv.json

    # Starship config
    starship:
      source: ~/dotfiles/config/starship.toml
      target: ~/.config/starship.toml

    # Alacritty config
    alacritty:
      source: ~/dotfiles/config/alacritty.toml
      target: ~/.config/alacritty/alacritty.toml

  # What groups users should be added
  user_groups:
    menno:
      - docker
      - libvirt
      - video
      - input

  # Keybinds to set into swhkd
  keybinds:
    terminal:
      shortcut: Ctrl + Alt + T
      command: alacritty
    screenshot:
      shortcut: Shift + Alt + 4
      command: flameshot gui
    missioncenter:
      shortcut: Ctrl + Shift + Escape
      command: flatpak run io.missioncenter.MissionCenter
  
  # Commands to run after login
  startup:
    - spotify
    - vesktop
    - dotf hotkey-daemon
    - brave-browser
    - steam
    - 1password
  
  # Fonts to install (Mostly tested with Nerd Fonts)
  fonts:
    Hack:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
      name: Hack
    Meslo:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip
      name: Meslo
    JetBrainsMono:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
      name: JetBrainsMono

  # Packages to install
  # Note: Uninstalling packages is not supported, if you remove a package from this list it will not be removed from the system!
  #       Likewise with flatpak remotes, apt repositories, etc.
  packages:
    # Supply a git_url and binary to install from source
    cargo:
      exa:
      lsd:
      bat:
      starship:
      ripgrep:
      fd-find:
      procs:
      bottom:
      Simple-Wayland-HotKey-Daemon:
        git_url: https://github.com/waycrate/swhkd.git
        binary: Simple-Wayland-HotKey-Daemon
      swhks:
        git_url: https://github.com/waycrate/swhkd.git
        binary: swhks

    pipx:
      - gnome-extensions-cli
      - bauh
      - shyaml

    apt:
      repos:
      apps:
        - zsh
        - solaar
        - git
        - curl
        - wget
        - gpg
        - nala
        - ca-certificates
        - gnupg-agent
        - software-properties-common
        - apt-transport-https
        - vim
        - sl
        - jq
        - libglvnd-dev
        - libwayland-dev
        - libseat-dev
        - libxkbcommon-dev
        - libinput-dev
        - udev
        - dbus
        - libdbus-1-dev
        - libsystemd-dev
        - libpixman-1-dev
        - libssl-dev
        - libflatpak-dev
        - libpulse-dev
        - libexpat1-dev
        - libfontconfig-dev
        - libfreetype-dev
        - mold
        - cargo
        - libgbm-dev
        - libclang-dev
        - libpipewire-0.3-dev
        - libpam0g-dev
        - openssh-server
        - build-essential
        - flatpak
        - meson
        - pipx
        - python3-nautilus
        - gettext
        - fzf
        - neofetch
        - screenfetch
        - screen
        - brave-browser
        - code
        - 1password
        - 1password-cli
        - spotify-client
        - flameshot
        - cmake
        - libsqlite3-dev
        - libudev-dev
        - libncursesw5-dev
        - libgdbm-dev
        - libc6-dev
        - libbz2-dev
        - libffi-dev
        - tk-dev
        - alacritty
        
