services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro

      ## Keep configs, scrapers, and plugins here.
      - /mnt/services/stash/config:/root/.stash
      ## Point this at your collection.
      - /mnt/stash:/data
      ## This is where your stash's metadata lives
      - /mnt/services/stash/metadata:/metadata
      ## Any other cache content.
      - /mnt/services/stash/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /mnt/services/stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/services/stash/generated:/generated
